CREATE TABLE HR.CLIENTS (
  CLIENT_ID NUMBER(4),
  CLIENT_NAME VARCHAR2(50 BYTE),
  MOBILE VARCHAR2(50 BYTE),
  ADDRESS VARCHAR2(100 BYTE),
  NID VARCHAR2(100 BYTE),
  CONSTRAINT CLIENTS_PK PRIMARY KEY (CLIENT_ID)
);

CREATE TABLE HR.CONTRACTS (
  CONTRACT_ID NUMBER,
  CONTRACT_STARTDATE DATE,
  CONTRACT_ENDDATE DATE,
  CONTRACT_TOTAL_FEES NUMBER(10, 2),
  CONTRACT_DEPOSIT_FEES NUMBER(10, 2),
  CLIENT_ID NUMBER,
  CONTRACT_PAYMENT_TYPE VARCHAR2(250 BYTE),
  NOTES VARCHAR2(4000 BYTE),
  CONSTRAINT CONTRACTS_PK PRIMARY KEY (CONTRACT_ID),
  CONSTRAINT CONTRACTS_R01 FOREIGN KEY (CLIENT_ID) REFERENCES HR.CLIENTS (CLIENT_ID)
);

CREATE TABLE HR.INSTALLMENTS_PAID (
  INSTALLMENT_ID NUMBER,
  CONTRACT_ID NUMBER,
  INSTALLMENT_DATE DATE,
  INSTALLMENT_AMOUNT NUMBER(10, 2),
  PAID NUMBER(1),
  CONSTRAINT INSTALLMENTS_PAID_PK PRIMARY KEY (INSTALLMENT_ID),
  CONSTRAINT INSTALLMENTS_PAID_R01 FOREIGN KEY (CONTRACT_ID) REFERENCES HR.CONTRACTS (CONTRACT_ID)
);

CREATE SEQUENCE HR.INSTALLMENTS_PAID_SEQ START WITH 1 MAXVALUE 999999999999999999999999999;
